# Generated by Django 3.0.2 on 2020-02-02 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=500000.0, max_digits=19)),
                ('value_in_stocks', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('diff', models.DecimalField(decimal_places=2, max_digits=19)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('invested', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('isBought', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('logtime', models.DateTimeField()),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stock')),
            ],
        ),
    ]
